import { CountryList } from "@/shared/interface/country-interface";

/**
 * @constant LIST_COUNTRY
 * @description List of countries
 */
export const LIST_COUNTRY: CountryList = {
  AF: {
    es: "Afganistán",
    en: "Afghanistan",
    money: { symbol: "؋", name: "Afghani", code: "AFN" },
    flag: "🇦🇫",
    phone: "93",
    key: "AF",
  },
  AL: {
    es: "Albania",
    en: "Albania",
    money: { symbol: "L", name: "Lek", code: "ALL" },
    flag: "🇦🇱",
    phone: "355",
    key: "AL",
  },
  DZ: {
    es: "Argelia",
    en: "Algeria",
    money: { symbol: "د.ج", name: "Dinar argelino", code: "DZD" },
    flag: "🇩🇿",
    phone: "213",
    key: "DZ",
  },
  AD: {
    es: "Andorra",
    en: "Andorra",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇦🇩",
    phone: "376",
    key: "AD",
  },
  AO: {
    es: "Angola",
    en: "Angola",
    money: { symbol: "Kz", name: "Kwanza", code: "AOA" },
    flag: "🇦🇴",
    phone: "244",
    key: "AO",
  },
  AG: {
    es: "Antigua y Barbuda",
    en: "Antigua and Barbuda",
    money: { symbol: "$", name: "Dólar del Caribe Oriental", code: "XCD" },
    flag: "🇦🇬",
    phone: "1268",
    key: "AG",
  },
  AR: {
    es: "Argentina",
    en: "Argentina",
    money: { symbol: "$", name: "Peso argentino", code: "ARS" },
    flag: "🇦🇷",
    phone: "54",
    key: "AR",
  },
  AM: {
    es: "Armenia",
    en: "Armenia",
    money: { symbol: "֏", name: "Dram", code: "AMD" },
    flag: "🇦🇲",
    phone: "374",
    key: "AM",
  },
  AU: {
    es: "Australia",
    en: "Australia",
    money: { symbol: "$", name: "Dólar australiano", code: "AUD" },
    flag: "🇦🇺",
    phone: "61",
    key: "AU",
  },
  AT: {
    es: "Austria",
    en: "Austria",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇦🇹",
    phone: "43",
    key: "AT",
  },
  AZ: {
    es: "Azerbaiyán",
    en: "Azerbaijan",
    money: { symbol: "₼", name: "Manat azerí", code: "AZN" },
    flag: "🇦🇿",
    phone: "994",
    key: "AZ",
  },
  BS: {
    es: "Bahamas",
    en: "Bahamas",
    money: { symbol: "$", name: "Dólar bahameño", code: "BSD" },
    flag: "🇧🇸",
    phone: "1242",
    key: "BS",
  },
  BH: {
    es: "Bahréin",
    en: "Bahrain",
    money: { symbol: ".د.ب", name: "Dinar bahreiní", code: "BHD" },
    flag: "🇧🇭",
    phone: "973",
    key: "BH",
  },
  BD: {
    es: "Bangladés",
    en: "Bangladesh",
    money: { symbol: "৳", name: "Taka", code: "BDT" },
    flag: "🇧🇩",
    phone: "880",
    key: "BD",
  },
  BB: {
    es: "Barbados",
    en: "Barbados",
    money: { symbol: "$", name: "Dólar de Barbados", code: "BBD" },
    flag: "🇧🇧",
    phone: "1246",
    key: "BB",
  },
  BY: {
    es: "Bielorrusia",
    en: "Belarus",
    money: { symbol: "Br", name: "Rublo bielorruso", code: "BYN" },
    flag: "🇧🇾",
    phone: "375",
    key: "BY",
  },
  BE: {
    es: "Bélgica",
    en: "Belgium",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇧🇪",
    phone: "32",
    key: "BE",
  },
  BZ: {
    es: "Belice",
    en: "Belize",
    money: { symbol: "$", name: "Dólar beliceño", code: "BZD" },
    flag: "🇧🇿",
    phone: "501",
    key: "BZ",
  },
  BJ: {
    es: "Benín",
    en: "Benin",
    money: { symbol: "Fr", name: "Franco CFA BCEAO", code: "XOF" },
    flag: "🇧🇯",
    phone: "229",
    key: "BJ",
  },
  BT: {
    es: "Bután",
    en: "Bhutan",
    money: { symbol: "Nu.", name: "Ngultrum", code: "BTN" },
    flag: "🇧🇹",
    phone: "975",
    key: "BT",
  },
  BO: {
    es: "Bolivia",
    en: "Bolivia",
    money: { symbol: "Bs.", name: "Boliviano", code: "BOB" },
    flag: "🇧🇴",
    phone: "591",
    key: "BO",
  },
  BA: {
    es: "Bosnia y Herzegovina",
    en: "Bosnia and Herzegovina",
    money: { symbol: "KM", name: "Marco convertible", code: "BAM" },
    flag: "🇧🇦",
    phone: "387",
    key: "BA",
  },
  BW: {
    es: "Botsuana",
    en: "Botswana",
    money: { symbol: "P", name: "Pula", code: "BWP" },
    flag: "🇧🇼",
    phone: "267",
    key: "BW",
  },
  BR: {
    es: "Brasil",
    en: "Brazil",
    money: { symbol: "R$", name: "Real brasileño", code: "BRL" },
    flag: "🇧🇷",
    phone: "55",
    key: "BR",
  },
  BN: {
    es: "Brunéi",
    en: "Brunei",
    money: { symbol: "$", name: "Dólar de Brunéi", code: "BND" },
    flag: "🇧🇳",
    phone: "673",
    key: "BN",
  },
  BG: {
    es: "Bulgaria",
    en: "Bulgaria",
    money: { symbol: "лв", name: "Lev búlgaro", code: "BGN" },
    flag: "🇧🇬",
    phone: "359",
    key: "BG",
  },
  BF: {
    es: "Burkina Faso",
    en: "Burkina Faso",
    money: { symbol: "Fr", name: "Franco CFA BCEAO", code: "XOF" },
    flag: "🇧🇫",
    phone: "226",
    key: "BF",
  },
  BI: {
    es: "Burundi",
    en: "Burundi",
    money: { symbol: "Fr", name: "Franco burundés", code: "BIF" },
    flag: "🇧🇮",
    phone: "257",
    key: "BI",
  },
  CV: {
    es: "Cabo Verde",
    en: "Cabo Verde",
    money: { symbol: "Esc", name: "Escudo caboverdiano", code: "CVE" },
    flag: "🇨🇻",
    phone: "238",
    key: "CV",
  },
  KH: {
    es: "Camboya",
    en: "Cambodia",
    money: { symbol: "៛", name: "Riel", code: "KHR" },
    flag: "🇰🇭",
    phone: "855",
    key: "KH",
  },
  CM: {
    es: "Camerún",
    en: "Cameroon",
    money: { symbol: "Fr", name: "Franco CFA BEAC", code: "XAF" },
    flag: "🇨🇲",
    phone: "237",
    key: "CM",
  },
  CA: {
    es: "Canadá",
    en: "Canada",
    money: { symbol: "$", name: "Dólar canadiense", code: "CAD" },
    flag: "🇨🇦",
    phone: "1",
    key: "CA",
  },
  CF: {
    es: "República Centroafricana",
    en: "Central African Republic",
    money: { symbol: "Fr", name: "Franco CFA BEAC", code: "XAF" },
    flag: "🇨🇫",
    phone: "236",
    key: "CF",
  },
  TD: {
    es: "Chad",
    en: "Chad",
    money: { symbol: "Fr", name: "Franco CFA BEAC", code: "XAF" },
    flag: "🇹🇩",
    phone: "235",
    key: "TD",
  },
  CL: {
    es: "Chile",
    en: "Chile",
    money: { symbol: "$", name: "Peso chileno", code: "CLP" },
    flag: "🇨🇱",
    phone: "56",
    key: "CL",
  },
  CN: {
    es: "China",
    en: "China",
    money: { symbol: "¥", name: "Yuan renminbi", code: "CNY" },
    flag: "🇨🇳",
    phone: "86",
    key: "CN",
  },
  CO: {
    es: "Colombia",
    en: "Colombia",
    money: { symbol: "$", name: "Peso colombiano", code: "COP" },
    flag: "🇨🇴",
    phone: "57",
    key: "CO",
  },
  KM: {
    es: "Comoras",
    en: "Comoros",
    money: { symbol: "Fr", name: "Franco comorense", code: "KMF" },
    flag: "🇰🇲",
    phone: "269",
    key: "KM",
  },
  CG: {
    es: "República del Congo",
    en: "Republic of the Congo",
    money: { symbol: "Fr", name: "Franco CFA BEAC", code: "XAF" },
    flag: "🇨🇬",
    phone: "242",
    key: "CG",
  },
  CD: {
    es: "República Democrática del Congo",
    en: "Democratic Republic of the Congo",
    money: { symbol: "Fr", name: "Franco congoleño", code: "CDF" },
    flag: "🇨🇩",
    phone: "243",
    key: "CD",
  },
  CR: {
    es: "Costa Rica",
    en: "Costa Rica",
    money: { symbol: "₡", name: "Colón costarricense", code: "CRC" },
    flag: "🇨🇷",
    phone: "506",
    key: "CR",
  },
  HR: {
    es: "Croacia",
    en: "Croatia",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇭🇷",
    phone: "385",
    key: "HR",
  },
  CU: {
    es: "Cuba",
    en: "Cuba",
    money: { symbol: "$", name: "Peso cubano", code: "CUP" },
    flag: "🇨🇺",
    phone: "53",
    key: "CU",
  },
  CY: {
    es: "Chipre",
    en: "Cyprus",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇨🇾",
    phone: "357",
    key: "CY",
  },
  CZ: {
    es: "República Checa",
    en: "Czech Republic",
    money: { symbol: "Kč", name: "Corona checa", code: "CZK" },
    flag: "🇨🇿",
    phone: "420",
    key: "CZ",
  },
  DK: {
    es: "Dinamarca",
    en: "Denmark",
    money: { symbol: "kr", name: "Corona danesa", code: "DKK" },
    flag: "🇩🇰",
    phone: "45",
    key: "DK",
  },
  DJ: {
    es: "Yibuti",
    en: "Djibouti",
    money: { symbol: "Fr", name: "Franco yibutiano", code: "DJF" },
    flag: "🇩🇯",
    phone: "253",
    key: "DJ",
  },
  DM: {
    es: "Dominica",
    en: "Dominica",
    money: { symbol: "$", name: "Dólar del Caribe Oriental", code: "XCD" },
    flag: "🇩🇲",
    phone: "1767",
    key: "DM",
  },
  DO: {
    es: "República Dominicana",
    en: "Dominican Republic",
    money: { symbol: "$", name: "Peso dominicano", code: "DOP" },
    flag: "🇩🇴",
    phone: "1-809",
    key: "DO",
  },
  EC: {
    es: "Ecuador",
    en: "Ecuador",
    money: { symbol: "$", name: "Dólar estadounidense", code: "USD" },
    flag: "🇪🇨",
    phone: "593",
    key: "EC",
  },
  EG: {
    es: "Egipto",
    en: "Egypt",
    money: { symbol: "£", name: "Libra egipcia", code: "EGP" },
    flag: "🇪🇬",
    phone: "20",
    key: "EG",
  },
  SV: {
    es: "El Salvador",
    en: "El Salvador",
    money: { symbol: "$", name: "Dólar estadounidense", code: "USD" },
    flag: "🇸🇻",
    phone: "503",
    key: "SV",
  },
  GQ: {
    es: "Guinea Ecuatorial",
    en: "Equatorial Guinea",
    money: { symbol: "Fr", name: "Franco CFA BEAC", code: "XAF" },
    flag: "🇬🇶",
    phone: "240",
    key: "GQ",
  },
  ER: {
    es: "Eritrea",
    en: "Eritrea",
    money: { symbol: "Nfk", name: "Nakfa", code: "ERN" },
    flag: "🇪🇷",
    phone: "291",
    key: "ER",
  },
  EE: {
    es: "Estonia",
    en: "Estonia",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇪🇪",
    phone: "372",
    key: "EE",
  },
  SZ: {
    es: "Eswatini",
    en: "Eswatini",
    money: { symbol: "E", name: "Lilangeni", code: "SZL" },
    flag: "🇸🇿",
    phone: "268",
    key: "SZ",
  },
  ET: {
    es: "Etiopía",
    en: "Ethiopia",
    money: { symbol: "ብር", name: "Birr etíope", code: "ETB" },
    flag: "🇪🇹",
    phone: "251",
    key: "ET",
  },
  FJ: {
    es: "Fiyi",
    en: "Fiji",
    money: { symbol: "$", name: "Dólar fiyiano", code: "FJD" },
    flag: "🇫🇯",
    phone: "679",
    key: "FJ",
  },
  FI: {
    es: "Finlandia",
    en: "Finland",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇫🇮",
    phone: "358",
    key: "FI",
  },
  FR: {
    es: "Francia",
    en: "France",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇫🇷",
    phone: "33",
    key: "FR",
  },
  GA: {
    es: "Gabón",
    en: "Gabon",
    money: { symbol: "Fr", name: "Franco CFA BEAC", code: "XAF" },
    flag: "🇬🇦",
    phone: "241",
    key: "GA",
  },
  GM: {
    es: "Gambia",
    en: "Gambia",
    money: { symbol: "D", name: "Dalasi", code: "GMD" },
    flag: "🇬🇲",
    phone: "220",
    key: "GM",
  },
  GE: {
    es: "Georgia",
    en: "Georgia",
    money: { symbol: "₾", name: "Lari", code: "GEL" },
    flag: "🇬🇪",
    phone: "995",
    key: "GE",
  },
  DE: {
    es: "Alemania",
    en: "Germany",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇩🇪",
    phone: "49",
    key: "DE",
  },
  GH: {
    es: "Ghana",
    en: "Ghana",
    money: { symbol: "₵", name: "Cedi ghanés", code: "GHS" },
    flag: "🇬🇭",
    phone: "233",
    key: "GH",
  },
  GI: {
    es: "Gibraltar",
    en: "Gibraltar",
    money: { symbol: "£", name: "Libra de Gibraltar", code: "GIP" },
    flag: "🇬🇮",
    phone: "350",
    key: "GI",
  },
  GR: {
    es: "Grecia",
    en: "Greece",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇬🇷",
    phone: "30",
    key: "GR",
  },
  GL: {
    es: "Groenlandia",
    en: "Greenland",
    money: { symbol: "kr", name: "Corona groenlandesa", code: "DKK" },
    flag: "🇬🇱",
    phone: "299",
    key: "GL",
  },
  GT: {
    es: "Guatemala",
    en: "Guatemala",
    money: { symbol: "Q", name: "Quetzal", code: "GTQ" },
    flag: "🇵🇪",
    phone: "502",
    key: "GT",
  },
  GN: {
    es: "Guinea",
    en: "Guinea",
    money: { symbol: "Fr", name: "Franco guineano", code: "GNF" },
    flag: "🇬🇳",
    phone: "224",
    key: "GN",
  },
  GW: {
    es: "Guinea-Bisáu",
    en: "Guinea-Bissau",
    money: { symbol: "Fr", name: "Franco CFA BCEAO", code: "XOF" },
    flag: "🇬🇼",
    phone: "245",
    key: "GW",
  },
  GY: {
    es: "Guyana",
    en: "Guyana",
    money: { symbol: "$", name: "Dólar guyanés", code: "GYD" },
    flag: "🇬🇾",
    phone: "592",
    key: "GY",
  },
  HT: {
    es: "Haití",
    en: "Haiti",
    money: { symbol: "G", name: "Gourde", code: "HTG" },
    flag: "🇭🇹",
    phone: "509",
    key: "HT",
  },
  HN: {
    es: "Honduras",
    en: "Honduras",
    money: { symbol: "L", name: "Lempira", code: "HNL" },
    flag: "🇭🇳",
    phone: "504",
    key: "HN",
  },
  HK: {
    es: "Hong Kong",
    en: "Hong Kong",
    money: { symbol: "$", name: "Dólar de Hong Kong", code: "HKD" },
    flag: "🇭🇰",
    phone: "852",
    key: "HK",
  },
  HU: {
    es: "Hungría",
    en: "Hungary",
    money: { symbol: "Ft", name: "Forinto", code: "HUF" },
    flag: "🇭🇺",
    phone: "36",
    key: "HU",
  },
  IS: {
    es: "Islandia",
    en: "Iceland",
    money: { symbol: "kr", name: "Corona islandesa", code: "ISK" },
    flag: "🇮🇸",
    phone: "354",
    key: "IS",
  },
  IN: {
    es: "India",
    en: "India",
    money: { symbol: "₹", name: "Rupia india", code: "INR" },
    flag: "🇮🇳",
    phone: "91",
    key: "IN",
  },
  ID: {
    es: "Indonesia",
    en: "Indonesia",
    money: { symbol: "Rp", name: "Rupia indonesia", code: "IDR" },
    flag: "🇮🇩",
    phone: "62",
    key: "ID",
  },
  IR: {
    es: "Irán",
    en: "Iran",
    money: { symbol: "﷼", name: "Rial iraní", code: "IRR" },
    flag: "🇮🇷",
    phone: "98",
    key: "IR",
  },
  IQ: {
    es: "Irak",
    en: "Iraq",
    money: { symbol: "ع.د", name: "Dinar iraquí", code: "IQD" },
    flag: "🇮🇶",
    phone: "964",
    key: "IQ",
  },
  IE: {
    es: "Irlanda",
    en: "Ireland",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇮🇪",
    phone: "353",
    key: "IE",
  },
  IL: {
    es: "Israel",
    en: "Israel",
    money: { symbol: "₪", name: "Shekel israelí", code: "ILS" },
    flag: "🇮🇱",
    phone: "972",
    key: "IL",
  },
  IT: {
    es: "Italia",
    en: "Italy",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇮🇹",
    phone: "39",
    key: "IT",
  },
  JM: {
    es: "Jamaica",
    en: "Jamaica",
    money: { symbol: "J$", name: "Dólar jamaicano", code: "JMD" },
    flag: "🇯🇲",
    phone: "1876",
    key: "JM",
  },
  JP: {
    es: "Japón",
    en: "Japan",
    money: { symbol: "¥", name: "Yen japonés", code: "JPY" },
    flag: "🇯🇵",
    phone: "81",
    key: "JP",
  },
  JO: {
    es: "Jordania",
    en: "Jordan",
    money: { symbol: "د.أ", name: "Dinar jordano", code: "JOD" },
    flag: "🇯🇴",
    phone: "962",
    key: "JO",
  },
  KZ: {
    es: "Kazajistán",
    en: "Kazakhstan",
    money: { symbol: "₸", name: "Tenge", code: "KZT" },
    flag: "🇰🇿",
    phone: "7",
    key: "KZ",
  },
  KE: {
    es: "Kenia",
    en: "Kenya",
    money: { symbol: "KSh", name: "Chelín keniano", code: "KES" },
    flag: "🇰🇪",
    phone: "254",
    key: "KE",
  },
  KI: {
    es: "Kiribati",
    en: "Kiribati",
    money: { symbol: "$", name: "Dólar australiano", code: "AUD" },
    flag: "🇰🇮",
    phone: "686",
    key: "KI",
  },
  KP: {
    es: "Corea del Norte",
    en: "North Korea",
    money: { symbol: "₩", name: "Won norcoreano", code: "KPW" },
    flag: "🇰🇵",
    phone: "850",
    key: "KP",
  },
  KR: {
    es: "Corea del Sur",
    en: "South Korea",
    money: { symbol: "₩", name: "Won surcoreano", code: "KRW" },
    flag: "🇰🇷",
    phone: "82",
    key: "KR",
  },
  KW: {
    es: "Kuwait",
    en: "Kuwait",
    money: { symbol: "د.ك", name: "Dinar kuwaití", code: "KWD" },
    flag: "🇰🇼",
    phone: "965",
    key: "KW",
  },
  KG: {
    es: "Kirguistán",
    en: "Kyrgyzstan",
    money: { symbol: "лв", name: "Som", code: "KGS" },
    flag: "🇰🇬",
    phone: "996",
    key: "KG",
  },
  LA: {
    es: "Laos",
    en: "Laos",
    money: { symbol: "₭", name: "Kip laosiano", code: "LAK" },
    flag: "🇱🇦",
    phone: "856",
    key: "LA",
  },
  LV: {
    es: "Letonia",
    en: "Latvia",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇱🇻",
    phone: "371",
    key: "LV",
  },
  LB: {
    es: "Líbano",
    en: "Lebanon",
    money: { symbol: "ل.ل", name: "Libra libanesa", code: "LBP" },
    flag: "🇱🇧",
    phone: "961",
    key: "LB",
  },
  LS: {
    es: "Lesoto",
    en: "Lesotho",
    money: { symbol: "M", name: "Loti", code: "LSL" },
    flag: "🇱🇸",
    phone: "266",
    key: "LS",
  },
  LR: {
    es: "Liberia",
    en: "Liberia",
    money: { symbol: "$", name: "Dólar liberiano", code: "LRD" },
    flag: "🇱🇸",
    phone: "231",
    key: "LR",
  },
  LY: {
    es: "Libia",
    en: "Libya",
    money: { symbol: "ل.د", name: "Dinar libio", code: "LYD" },
    flag: "🇱🇾",
    phone: "218",
    key: "LY",
  },
  LI: {
    es: "Liechtenstein",
    en: "Liechtenstein",
    money: { symbol: "CHF", name: "Franco suizo", code: "CHF" },
    flag: "🇱🇮",
    phone: "423",
    key: "LI",
  },
  LT: {
    es: "Lituania",
    en: "Lithuania",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇱🇹",
    phone: "370",
    key: "LT",
  },
  LU: {
    es: "Luxemburgo",
    en: "Luxembourg",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇱🇺",
    phone: "352",
    key: "LU",
  },
  MO: {
    es: "Macao",
    en: "Macau",
    money: { symbol: "$", name: "Dólar de Macao", code: "MOP" },
    flag: "🇲🇴",
    phone: "853",
    key: "MO",
  },
  MK: {
    es: "Macedonia del Norte",
    en: "North Macedonia",
    money: { symbol: "ден", name: "Denar", code: "MKD" },
    flag: "🇲🇰",
    phone: "389",
    key: "MK",
  },
  MG: {
    es: "Madagascar",
    en: "Madagascar",
    money: { symbol: "Ar", name: "Ariary malgache", code: "MGA" },
    flag: "🇲🇬",
    phone: "261",
    key: "MG",
  },
  MW: {
    es: "Malawi",
    en: "Malawi",
    money: { symbol: "MK", name: "Kwacha malauí", code: "MWK" },
    flag: "🇲🇼",
    phone: "265",
    key: "MW",
  },
  MY: {
    es: "Malasia",
    en: "Malaysia",
    money: { symbol: "RM", name: "Ringgit", code: "MYR" },
    flag: "🇲🇾",
    phone: "60",
    key: "MY",
  },
  MV: {
    es: "Maldivas",
    en: "Maldives",
    money: { symbol: "Rf", name: "Rufiyaa maldiva", code: "MVR" },
    flag: "🇲🇻",
    phone: "960",
    key: "MV",
  },
  ML: {
    es: "Malí",
    en: "Mali",
    money: { symbol: "Fr", name: "Franco CFA BCEAO", code: "XOF" },
    flag: "🇲🇱",
    phone: "223",
    key: "ML",
  },
  MT: {
    es: "Malta",
    en: "Malta",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇲🇹",
    phone: "356",
    key: "MT",
  },
  MH: {
    es: "Islas Marshall",
    en: "Marshall Islands",
    money: { symbol: "$", name: "Dólar estadounidense", code: "USD" },
    flag: "🇲🇭",
    phone: "692",
    key: "MH",
  },
  MQ: {
    es: "Martinica",
    en: "Martinique",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇲🇶",
    phone: "596",
    key: "MQ",
  },
  MR: {
    es: "Mauritania",
    en: "Mauritania",
    money: { symbol: "UM", name: "Ouguiya", code: "MRU" },
    flag: "🇲🇷",
    phone: "222",
    key: "MR",
  },
  MU: {
    es: "Mauricio",
    en: "Mauritius",
    money: { symbol: "₨", name: "Rupia mauriciana", code: "MUR" },
    flag: "🇲🇺",
    phone: "230",
    key: "MU",
  },
  YT: {
    es: "Mayotte",
    en: "Mayotte",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇲🇶",
    phone: "269",
    key: "YT",
  },
  MX: {
    es: "México",
    en: "Mexico",
    money: { symbol: "$", name: "Peso mexicano", code: "MXN" },
    flag: "🇲🇽",
    phone: "52",
    key: "MX",
  },
  FM: {
    es: "Micronesia",
    en: "Micronesia",
    money: { symbol: "$", name: "Dólar estadounidense", code: "USD" },
    flag: "🇲🇫",
    phone: "691",
    key: "FM",
  },
  MD: {
    es: "Moldavia",
    en: "Moldova",
    money: { symbol: "L", name: "Leu moldavo", code: "MDL" },
    flag: "🇲🇩",
    phone: "373",
    key: "MD",
  },
  MC: {
    es: "Mónaco",
    en: "Monaco",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇲🇨",
    phone: "377",
    key: "MC",
  },
  MN: {
    es: "Mongolia",
    en: "Mongolia",
    money: { symbol: "₮", name: "Tugrik", code: "MNT" },
    flag: "🇲🇳",
    phone: "976",
    key: "MN",
  },
  ME: {
    es: "Montenegro",
    en: "Montenegro",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇲🇪",
    phone: "382",
    key: "ME",
  },
  MS: {
    es: "Montserrat",
    en: "Montserrat",
    money: { symbol: "$", name: "Dólar del Caribe Oriental", code: "XCD" },
    flag: "🇲🇸",
    phone: "1664",
    key: "MS",
  },
  MA: {
    es: "Marruecos",
    en: "Morocco",
    money: { symbol: "د.م.", name: "Dirham marroquí", code: "MAD" },
    flag: "🇲🇦",
    phone: "212",
    key: "MA",
  },
  MZ: {
    es: "Mozambique",
    en: "Mozambique",
    money: { symbol: "MT", name: "Metical", code: "MZN" },
    flag: "🇲🇿",
    phone: "258",
    key: "MZ",
  },
  MM: {
    es: "Birmania",
    en: "Myanmar",
    money: { symbol: "Ks", name: "Kyat", code: "MMK" },
    flag: "🇲🇲",
    phone: "95",
    key: "MM",
  },
  NA: {
    es: "Namibia",
    en: "Namibia",
    money: { symbol: "$", name: "Dólar namibio", code: "NAD" },
    flag: "🇳🇦",
    phone: "264",
    key: "NA",
  },
  NR: {
    es: "Nauru",
    en: "Nauru",
    money: { symbol: "$", name: "Dólar australiano", code: "AUD" },
    flag: "🇳🇷",
    phone: "674",
    key: "NR",
  },
  NP: {
    es: "Nepal",
    en: "Nepal",
    money: { symbol: "Rs", name: "Rupia nepalesa", code: "NPR" },
    flag: "🇳🇵",
    phone: "977",
    key: "NP",
  },
  NL: {
    es: "Países Bajos",
    en: "Netherlands",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇳🇱",
    phone: "31",
    key: "NL",
  },
  NC: {
    es: "Nueva Caledonia",
    en: "New Caledonia",
    money: { symbol: "$", name: "Dólar del Pacífico", code: "XPF" },
    flag: "🇳🇨",
    phone: "687",
    key: "NC",
  },
  NZ: {
    es: "Nueva Zelanda",
    en: "New Zealand",
    money: { symbol: "$", name: "Dólar neozelandés", code: "NZD" },
    flag: "🇳🇿",
    phone: "64",
    key: "NZ",
  },
  NI: {
    es: "Nicaragua",
    en: "Nicaragua",
    money: { symbol: "C$", name: "Córdoba nicaragüense", code: "NIO" },
    flag: "🇳🇮",
    phone: "505",
    key: "NI",
  },
  NE: {
    es: "Níger",
    en: "Niger",
    money: { symbol: "Fr", name: "Franco CFA BCEAO", code: "XOF" },
    flag: "🇳🇪",
    phone: "227",
    key: "NE",
  },
  NG: {
    es: "Nigeria",
    en: "Nigeria",
    money: { symbol: "₦", name: "Naira", code: "NGN" },
    flag: "🇳🇬",
    phone: "234",
    key: "NG",
  },
  NU: {
    es: "Niue",
    en: "Niue",
    money: { symbol: "$", name: "Dólar neozelandés", code: "NZD" },
    flag: "🇳🇺",
    phone: "683",
    key: "NU",
  },
  NF: {
    es: "Isla Norfolk",
    en: "Norfolk Island",
    money: { symbol: "$", name: "Dólar australiano", code: "AUD" },
    flag: "🇳🇫",
    phone: "672",
    key: "NF",
  },
  MP: {
    es: "Islas Marianas del Norte",
    en: "Northern Mariana Islands",
    money: { symbol: "$", name: "Dólar estadounidense", code: "USD" },
    flag: "🇲🇵",
    phone: "1670",
    key: "MP",
  },
  NO: {
    es: "Noruega",
    en: "Norway",
    money: { symbol: "kr", name: "Corona noruega", code: "NOK" },
    flag: "🇳🇴",
    phone: "47",
    key: "NO",
  },
  OM: {
    es: "Omán",
    en: "Oman",
    money: { symbol: "ر.ع.", name: "Rial omaní", code: "OMR" },
    flag: "🇴🇲",
    phone: "968",
    key: "OM",
  },
  PK: {
    es: "Pakistán",
    en: "Pakistan",
    money: { symbol: "₨", name: "Rupia pakistaní", code: "PKR" },
    flag: "🇵🇰",
    phone: "92",
    key: "PK",
  },
  PW: {
    es: "Palaú",
    en: "Palau",
    money: { symbol: "$", name: "Dólar estadounidense", code: "USD" },
    flag: "🇵🇼",
    phone: "680",
    key: "PW",
  },
  PS: {
    es: "Palestina",
    en: "Palestine",
    money: { symbol: "₪", name: "Shekel israelí", code: "ILS" },
    flag: "🇵🇸",
    phone: "970",
    key: "PS",
  },
  PA: {
    es: "Panamá",
    en: "Panama",
    money: { symbol: "B/.", name: "Balboa", code: "PAB" },
    flag: "🇵🇦",
    phone: "507",
    key: "PA",
  },
  PG: {
    es: "Papúa Nueva Guinea",
    en: "Papua New Guinea",
    money: { symbol: "K", name: "Kina", code: "PGK" },
    flag: "🇵🇬",
    phone: "675",
    key: "PG",
  },
  PY: {
    es: "Paraguay",
    en: "Paraguay",
    money: { symbol: "₲", name: "Guaraní", code: "PYG" },
    flag: "🇵🇾",
    phone: "595",
    key: "PY",
  },
  PE: {
    es: "Perú",
    en: "Peru",
    money: { symbol: "S/", name: "Sol", code: "PEN" },
    flag: "🇵🇪",
    phone: "51",
    key: "PE",
  },
  PH: {
    es: "Filipinas",
    en: "Philippines",
    money: { symbol: "₱", name: "Peso filipino", code: "PHP" },
    flag: "🇵🇭",
    phone: "63",
    key: "PH",
  },
  PN: {
    es: "Pitcairn",
    en: "Pitcairn Islands",
    money: { symbol: "$", name: "Dólar neozelandés", code: "NZD" },
    flag: "🇵🇳",
    phone: "64",
    key: "PN",
  },
  PL: {
    es: "Polonia",
    en: "Poland",
    money: { symbol: "zł", name: "Zloty", code: "PLN" },
    flag: "🇵🇱",
    phone: "48",
    key: "PL",
  },
  PT: {
    es: "Portugal",
    en: "Portugal",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇵🇹",
    phone: "351",
    key: "PT",
  },
  PR: {
    es: "Puerto Rico",
    en: "Puerto Rico",
    money: { symbol: "$", name: "Dólar estadounidense", code: "USD" },
    flag: "🇵🇷",
    phone: "1787",
    key: "PR",
  },
  QA: {
    es: "Catar",
    en: "Qatar",
    money: { symbol: "ر.ق", name: "Riyal qatarí", code: "QAR" },
    flag: "🇶🇦",
    phone: "974",
    key: "QA",
  },
  RE: {
    es: "Reunión",
    en: "Réunion",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇷🇪",
    phone: "262",
    key: "RE",
  },
  RO: {
    es: "Rumania",
    en: "Romania",
    money: { symbol: "lei", name: "Leu rumano", code: "RON" },
    flag: "🇷🇴",
    phone: "40",
    key: "RO",
  },
  RU: {
    es: "Rusia",
    en: "Russia",
    money: { symbol: "₽", name: "Rublo ruso", code: "RUB" },
    flag: "🇷🇺",
    phone: "7",
    key: "RU",
  },
  RW: {
    es: "Ruanda",
    en: "Rwanda",
    money: { symbol: "Fr", name: "Franco ruandés", code: "RWF" },
    flag: "🇷🇼",
    phone: "250",
    key: "RW",
  },
  BL: {
    es: "San Bartolomé",
    en: "Saint Barthelemy",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇧🇱",
    phone: "590",
    key: "BL",
  },
  SH: {
    es: "Santa Elena",
    en: "Saint Helena",
    money: { symbol: "£", name: "Libra de Santa Helena", code: "SHP" },
    flag: "🇱🇸",
    phone: "290",
    key: "SH",
  },
  KN: {
    es: "San Cristóbal y Nieves",
    en: "Saint Kitts and Nevis",
    money: { symbol: "$", name: "Dólar del Caribe Oriental", code: "XCD" },
    flag: "🇰🇳",
    phone: "1869",
    key: "KN",
  },
  LC: {
    es: "Santa Lucía",
    en: "Saint Lucia",
    money: { symbol: "$", name: "Dólar del Caribe Oriental", code: "XCD" },
    flag: "🇱🇨",
    phone: "1758",
    key: "LC",
  },
  MF: {
    es: "San Martín",
    en: "Saint Martin",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇲🇫",
    phone: "590",
    key: "MF",
  },
  PM: {
    es: "San Pedro y Miquelón",
    en: "Saint Pierre and Miquelon",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇵🇲",
    phone: "508",
    key: "PM",
  },
  VC: {
    es: "San Vicente y las Granadinas",
    en: "Saint Vincent and the Grenadines",
    money: { symbol: "$", name: "Dólar del Caribe Oriental", code: "XCD" },
    flag: "🇻🇨",
    phone: "1784",
    key: "VC",
  },
  WS: {
    es: "Samoa",
    en: "Samoa",
    money: { symbol: "WS$", name: "Tala samoano", code: "WST" },
    flag: "🇼🇸",
    phone: "685",
    key: "WS",
  },
  SM: {
    es: "San Marino",
    en: "San Marino",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇸🇲",
    phone: "378",
    key: "SM",
  },
  ST: {
    es: "Santo Tomé y Príncipe",
    en: "Sao Tome and Principe",
    money: { symbol: "Db", name: "Dobra", code: "STN" },
    flag: "🇲🇱",
    phone: "239",
    key: "ST",
  },
  SA: {
    es: "Arabia Saudita",
    en: "Saudi Arabia",
    money: { symbol: "ر.س", name: "Riyal saudí", code: "SAR" },
    flag: "🇸🇦",
    phone: "966",
    key: "SA",
  },
  SN: {
    es: "Senegal",
    en: "Senegal",
    money: { symbol: "Fr", name: "Franco CFA BCEAO", code: "XOF" },
    flag: "🇸🇳",
    phone: "221",
    key: "SN",
  },
  RS: {
    es: "Serbia",
    en: "Serbia",
    money: { symbol: "дин", name: "Dinar serbio", code: "RSD" },
    flag: "🇷🇸",
    phone: "381",
    key: "RS",
  },
  SC: {
    es: "Seychelles",
    en: "Seychelles",
    money: { symbol: "₨", name: "Rupia seychellense", code: "SCR" },
    flag: "🇸🇨",
    phone: "248",
    key: "SC",
  },
  SL: {
    es: "Sierra Leona",
    en: "Sierra Leone",
    money: { symbol: "Le", name: "Leona", code: "SLL" },
    flag: "🇸🇱",
    phone: "232",
    key: "SL",
  },
  SG: {
    es: "Singapur",
    en: "Singapore",
    money: { symbol: "S$", name: "Dólar de Singapur", code: "SGD" },
    flag: "🇸🇬",
    phone: "65",
    key: "SG",
  },
  SX: {
    es: "Sint Maarten",
    en: "Sint Maarten",
    money: { symbol: "ƒ", name: "Florín antillano", code: "ANG" },
    flag: "🇸🇽",
    phone: "1721",
    key: "SX",
  },
  SK: {
    es: "Eslovaquia",
    en: "Slovakia",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇸🇰",
    phone: "421",
    key: "SK",
  },
  SI: {
    es: "Eslovenia",
    en: "Slovenia",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇸🇮",
    phone: "386",
    key: "SI",
  },
  SB: {
    es: "Islas Salomón",
    en: "Solomon Islands",
    money: { symbol: "$", name: "Dólar de las Islas Salomón", code: "SBD" },
    flag: "🇸🇧",
    phone: "677",
    key: "SB",
  },
  SO: {
    es: "Somalia",
    en: "Somalia",
    money: { symbol: "S", name: "Shilling somalí", code: "SOS" },
    flag: "🇸🇴",
    phone: "252",
    key: "SO",
  },
  ZA: {
    es: "Sudáfrica",
    en: "South Africa",
    money: { symbol: "R", name: "Rand", code: "ZAR" },
    flag: "🇿🇦",
    phone: "27",
    key: "ZA",
  },
  GS: {
    es: "Islas Georgias del Sur y Sandwich del Sur",
    en: "South Georgia and the South Sandwich Islands",
    money: { symbol: "£", name: "Libra esterlina", code: "GBP" },
    flag: "🇬🇸",
    phone: "500",
    key: "GS",
  },
  SS: {
    es: "Sudán del Sur",
    en: "South Sudan",
    money: { symbol: "£", name: "Libra sursudanesa", code: "SSP" },
    flag: "🇸🇸",
    phone: "211",
    key: "SS",
  },
  ES: {
    es: "España",
    en: "Spain",
    money: { symbol: "€", name: "Euro", code: "EUR" },
    flag: "🇪🇸",
    phone: "34",
    key: "ES",
  },
  LK: {
    es: "Sri Lanka",
    en: "Sri Lanka",
    money: { symbol: "Rs", name: "Rupia de Sri Lanka", code: "LKR" },
    flag: "🇱🇰",
    phone: "94",
    key: "LK",
  },
  SD: {
    es: "Sudán",
    en: "Sudan",
    money: { symbol: "ج.س.", name: "Dinar sudanés", code: "SDG" },
    flag: "🇸🇩",
    phone: "249",
    key: "SD",
  },
  SR: {
    es: "Surinam",
    en: "Suriname",
    money: { symbol: "$", name: "Dólar de Surinam", code: "SRD" },
    flag: "🇸🇷",
    phone: "597",
    key: "SR",
  },
  SJ: {
    es: "Svalbard y Jan Mayen",
    en: "Svalbard and Jan Mayen",
    money: { symbol: "kr", name: "Corona noruega", code: "NOK" },
    flag: "🇯🇲",
    phone: "47",
    key: "SJ",
  },

  SE: {
    es: "Suecia",
    en: "Sweden",
    money: { symbol: "kr", name: "Corona sueca", code: "SEK" },
    flag: "🇸🇪",
    phone: "46",
    key: "SE",
  },
  CH: {
    es: "Suiza",
    en: "Switzerland",
    money: { symbol: "Fr", name: "Franco suizo", code: "CHF" },
    flag: "🇨🇭",
    phone: "41",
    key: "CH",
  },
  SY: {
    es: "Siria",
    en: "Syria",
    money: { symbol: "س.س.", name: "Libra siria", code: "SYP" },
    flag: "🇸🇾",
    phone: "963",
    key: "SY",
  },
  TW: {
    es: "Taiwán",
    en: "Taiwan",
    money: { symbol: "NT$", name: "Dólar nuevo taiwanés", code: "TWD" },
    flag: "🇹🇼",
    phone: "886",
    key: "TW",
  },
  TJ: {
    es: "Tayikistán",
    en: "Tajikistan",
    money: { symbol: "ЅМ", name: "Somoni", code: "TJS" },
    flag: "🇹🇯",
    phone: "992",
    key: "TJ",
  },
  TZ: {
    es: "Tanzania",
    en: "Tanzania",
    money: { symbol: "TSh", name: "Chelín tanzano", code: "TZS" },
    flag: "🇹🇿",
    phone: "255",
    key: "TZ",
  },
  TH: {
    es: "Tailandia",
    en: "Thailand",
    money: { symbol: "฿", name: "Baht tailandés", code: "THB" },
    flag: "🇹🇭",
    phone: "66",
    key: "TH",
  },
  TG: {
    es: "Togo",
    en: "Togo",
    money: { symbol: "Fr", name: "Franco CFA BCEAO", code: "XOF" },
    flag: "🇹🇬",
    phone: "228",
    key: "TG",
  },
  TK: {
    es: "Tokelau",
    en: "Tokelau",
    money: { symbol: "$", name: "Dólar neozelandés", code: "NZD" },
    flag: "🇹🇰",
    phone: "690",
    key: "TK",
  },
  TO: {
    es: "Tonga",
    en: "Tonga",
    money: { symbol: "T$", name: "Paʻanga", code: "TOP" },
    flag: "🇹🇴",
    phone: "676",
    key: "TO",
  },
  TT: {
    es: "Trinidad y Tobago",
    en: "Trinidad and Tobago",
    money: { symbol: "$", name: "Dólar de Trinidad y Tobago", code: "TTD" },
    flag: "🇹🇹",
    phone: "1868",
    key: "TT",
  },
  TN: {
    es: "Túnez",
    en: "Tunisia",
    money: { symbol: "د.ت", name: "Dinar tunecino", code: "TND" },
    flag: "🇹🇳",
    phone: "216",
    key: "TN",
  },
  TR: {
    es: "Turquía",
    en: "Turkey",
    money: { symbol: "₺", name: "Lira turca", code: "TRY" },
    flag: "🇹🇷",
    phone: "90",
    key: "TR",
  },
  TM: {
    es: "Turkmenistán",
    en: "Turkmenistan",
    money: { symbol: "m", name: "Manat turcomano", code: "TMT" },
    flag: "🇹🇲",
    phone: "993",
    key: "TM",
  },
  TC: {
    es: "Islas Turcas y Caicos",
    en: "Turks and Caicos Islands",
    money: { symbol: "$", name: "Dólar de las Islas Turcas y Caicos", code: "USD" },
    flag: "🇹🇨",
    phone: "1649",
    key: "TC",
  },
  TV: {
    es: "Tuvalu",
    en: "Tuvalu",
    money: { symbol: "$", name: "Dólar australiano", code: "AUD" },
    flag: "🇹🇻",
    phone: "688",
    key: "TV",
  },
  UG: {
    es: "Uganda",
    en: "Uganda",
    money: { symbol: "USh", name: "Chelín ugandés", code: "UGX" },
    flag: "🇺🇬",
    phone: "256",
    key: "UG",
  },
  UA: {
    es: "Ucrania",
    en: "Ukraine",
    money: { symbol: "₴", name: "Grivna", code: "UAH" },
    flag: "🇺🇦",
    phone: "380",
    key: "UA",
  },
  AE: {
    es: "Emiratos Árabes Unidos",
    en: "United Arab Emirates",
    money: { symbol: "د.إ", name: "Dirham de los Emiratos Árabes Unidos", code: "AED" },
    flag: "🇦🇪",
    phone: "971",
    key: "AE",
  },
  GB: {
    es: "Reino Unido",
    en: "United Kingdom",
    money: { symbol: "£", name: "Libra esterlina", code: "GBP" },
    flag: "🇬🇧",
    phone: "44",
    key: "GB",
  },
  US: {
    es: "Estados Unidos",
    en: "United States",
    money: { symbol: "$", name: "Dólar estadounidense", code: "USD" },
    flag: "🇺🇸",
    phone: "1",
    key: "US",
  },
  UY: {
    es: "Uruguay",
    en: "Uruguay",
    money: { symbol: "$", name: "Peso uruguayo", code: "UYU" },
    flag: "🇺🇾",
    phone: "598",
    key: "UY",
  },
  UZ: {
    es: "Uzbekistán",
    en: "Uzbekistan",
    money: { symbol: "лв", name: "Som uzbeko", code: "UZS" },
    flag: "🇺🇿",
    phone: "998",
    key: "UZ",
  },
  VU: {
    es: "Vanuatu",
    en: "Vanuatu",
    money: { symbol: "Vt", name: "Vatu", code: "VUV" },
    flag: "🇻🇺",
    phone: "678",
    key: "VU",
  },
  VE: {
    es: "Venezuela",
    en: "Venezuela",
    money: { symbol: "Bs", name: "Bolívar", code: "VES" },
    flag: "🇻🇪",
    phone: "58",
    key: "VE",
  },
  VN: {
    es: "Vietnam",
    en: "Vietnam",
    money: { symbol: "₫", name: "Dong vietnamita", code: "VND" },
    flag: "🇻🇳",
    phone: "84",
    key: "VN",
  },
  WF: {
    es: "Wallis y Futuna",
    en: "Wallis and Futuna",
    money: { symbol: "$", name: "Dólar del Pacífico", code: "XPF" },
    flag: "🇼🇫",
    phone: "681",
    key: "WF",
  },
  EH: {
    es: "Sáhara Occidental",
    en: "Western Sahara",
    money: { symbol: "MAD", name: "Dirham marroquí", code: "MAD" },
    flag: "🇪🇭",
    phone: "212",
    key: "EH",
  },
  YE: {
    es: "Yemen",
    en: "Yemen",
    money: { symbol: "ر.ي", name: "Rial yemení", code: "YER" },
    flag: "🇾🇪",
    phone: "967",
    key: "YE",
  },
  ZM: {
    es: "Zambia",
    en: "Zambia",
    money: { symbol: "ZK", name: "Kwacha zambiano", code: "ZMW" },
    flag: "🇿🇲",
    phone: "260",
    key: "ZM",
  },
  ZW: {
    es: "Zimbabue",
    en: "Zimbabwe",
    money: { symbol: "Z$", name: "Dólar zimbabuense", code: "ZWL" },
    flag: "🇿🇼",
    phone: "263",
    key: "ZW",
  },
};
